import inquirer from 'inquirer'

// Stores
import { ShellArgumentsStore } from '../modules/index'

async function promptForMissingOptions() {
  const questions = []

  const {
    commitMsg,
    sendCommit,
    sendEmail
  } = ShellArgumentsStore

  if (commitMsg === null) {
    // TODO: move AUTOGENERATED to the global config
    questions.push({
      type: 'input',
      name: 'commitMsg',
      message: 'Please provide the commit message',
      default: 'AUTOGENERATED'
    })
  }
  if (sendCommit === null) {
    questions.push({
      type: 'confirm',
      name: 'sendCommit',
      message: 'Do you want to send commit?',
      default: 'true'
    })
  }
  if (sendEmail === null) {
    questions.push({
      type: 'confirm',
      name: 'sendEmail',
      message: 'Do you want to send email?',
      default: 'true'
    })
  }

  const answers = await inquirer.prompt(questions)

  ShellArgumentsStore.setCommitMessage(commitMsg || answers.commitMsg)
  ShellArgumentsStore.setSendCommit(answers.sendCommit || sendCommit)
  ShellArgumentsStore.setSendEmail(answers.sendEmail || sendEmail)

  return true
}

export { promptForMissingOptions }
