import inquirer from 'inquirer'

// Stores
import { ShellArgumentsStore, FilesInfoStore } from '../modules/index'

async function promptForMissingOptions() {
  const questions = []

  const { commitMsg } = ShellArgumentsStore

  if (!commitMsg) {
    questions.push({
      type: 'input',
      name: 'commitMsg',
      message: 'Please provide the commit message',
      default: 'AUTOGENERATED'
    })
  }

  const answers = await inquirer.prompt(questions)

  ShellArgumentsStore.setCommitMessage(commitMsg || answers.commitMsg)

  return true
}

export { promptForMissingOptions }
