import inquirer from 'inquirer'

// Stores
import { ShellArgumentsStore } from '../modules/index'

async function promptForMissingOptions() {
  const questions = []

  const {
    sendCommit,
    commitMsg,
    sendEmail,
    emailMsg
  } = ShellArgumentsStore

  if (!sendCommit) {
    questions.push({
      type: 'confirm',
      name: 'sendCommit',
      message: 'Do you want to send commit?',
      default: 'true'
    })
  }

  if (!commitMsg) {
    // TODO: move AUTOGENERATED to the global config
    questions.push({
      type: 'input',
      name: 'commitMsg',
      message: 'Provide the COMMIT message',
      default: 'AUTOGENERATED'
    })
  }

  if (!sendEmail) {
    questions.push({
      type: 'confirm',
      name: 'sendEmail',
      message: 'Do you want to send email?',
      default: 'true'
    })
  }

  if (!emailMsg) {
    // TODO: move AUTOGENERATED to the global config
    questions.push({
      type: 'input',
      name: 'emailMsg',
      message: 'Provide the EMAIL message',
      default: 'AUTOGENERATED email'
    })
  }

  const answers = await inquirer.prompt(questions)

  ShellArgumentsStore.setSendCommit(sendCommit || answers.sendCommit)
  ShellArgumentsStore.setCommitMessage(commitMsg || answers.commitMsg)
  ShellArgumentsStore.setSendEmail(sendEmail || answers.sendEmail)
  ShellArgumentsStore.setEmailMessage(sendEmail || answers.emailMsg)

  return true
}

export { promptForMissingOptions }
